### ISSUE TITLE
Improved HTML highlighting

### ISSUE THREAD

**Issue by Temptin** [jpo/vim-railscasts-theme#14]
Hey man, thanks a lot for this theme. It's exactly what I was looking for; nice, earthy tones and good contrast between different elements.

However, it has an issue. When Javascript is contained in a HTML file, the syntax highlighting is crippled in VIM (that's a fact of life and not related to your theme). Most severely, it sets all Javascript variable names to the "Special" color.

In this case, "Special" means a really difficult to read dark green (even worse if your terminal has a transparent background like mine does; it's nearly unreadable, but in my example below I use a pure black). The "Special" color in the theme is only meant to be used for little single characters here and there, and not for the main code, which is why it's such an awful color when it's suddenly applied to *all* variable names.

So I went through most of the 255 "cterm" colors to find a really nicely contrasting, bright-but-not-too-bright color that fits in well and makes VIM behave when editing .html files with embedded code, as well as working perfectly with transparent terminals. Here's the before and after (non-transparent terminal):

![before_and_after](https://cloud.githubusercontent.com/assets/12382119/9023747/97c34e38-38a9-11e5-88f5-0b05171aa534.png)

I made sure it still looks perfect in all other languages such as .rb files, .js, .php etc, so that "Special" doesn't lose its main purpose of highlighting special characters. In fact I think it looks much better in those languages too, since the lighter blue makes the special characters that "Special" is intended for stand out!

Here is the change (for both GUI and terminal VIM):
```
hi Special                   guifg=#50a19f ctermfg=73
```

I'll leave it up to you whether you want to commit the change or not. I've already done it on my local copy since the colorscheme was unusable for .html editing before this change. ;-)

**Comment by jpo** [comment]
Thanks for the feedback. I really appreciate it. Honestly, most of the credit should go to Ryan Bates, who created the original Railscasts theme, and to the contributors to this project.

Anyway, I just wanted to let you know that I'll be looking into this next week. I'd like to test this out on a few of my personal projects. I surprised that I haven't run across this before.

**Comment by Temptin** [comment]
No problem. I figured I'd shoot the change upstream since it made such a dramatic difference for the theme's usability.

Maybe the GUI version of VIM ships with a better .html syntax highlighter, which has a better "embedded javascript" parser and colors them differently? So a good starting point would be to check which color is applied by the syntax highlighter in gVim vs VIM. If they differ, then that would explain why you haven't encountered it.

I use a Mac and only use the terminal version of VIM, so I can't check if they differ. Macs ship with the standard VIM and its standard set of highlighters, but the GUI version of VIM is a different project and may have done its own tweaks to the highlighting rules.

$ vim -version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  5 2014 21:00:28)

PS: Ahh, an answer at last! It *is* properly spelled "VIM" all capitalized! I've been wondering about that. ;-)

**Comment by jpo** [comment]
Rather than changing the colorscheme, I think a better option would be to install the [Vim-Javascript](https://github.com/pangloss/vim-javascript) plugin which provides improved syntax highlighting for Javascript. It looks much better than simply changing the JavaScript highlight group in the colorscheme file.

![screen shot 2016-02-09 at 8 39 50 pm](https://cloud.githubusercontent.com/assets/28533/12936606/196484b0-cf6e-11e5-80cf-a57d05710dd4.png)
